build: off

platform:
- x64

before_test:
- set ORIG_PATH=%PATH%
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- set PATH=%ORIG_PATH%
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    TMP: "c:\\tmp"

  matrix:
   - PYV: "34"
     STACK_FLAGS: "--arch i386 --resolver lts-6.35"
     MINGW_PATH_PART: "C:\\MinGW\\bin;"
     CONDA_DEPENDENCIES: "libpython"
# Don't do these builds (reduce load on CI servers)
#   - PYV: "34"
#     STACK_FLAGS: "--arch i386 --resolver lts-9.21"
#     MINGW_PATH_PART: "C:\\MinGW\\bin;"
#     CONDA_DEPENDENCIES: "libpython"
#   - PYV: "34"
#     STACK_FLAGS: "--arch i386 --resolver lts-11.22"
#     MINGW_PATH_PART: "C:\\MinGW\\bin;"
#     CONDA_DEPENDENCIES: "libpython"
#   - PYV: "34"
#     STACK_FLAGS: "--arch i386 --resolver lts-12.26"
#     MINGW_PATH_PART: "C:\\MinGW\\bin;"
#     CONDA_DEPENDENCIES: "libpython"
   - PYV: "34"
     STACK_FLAGS: "--arch i386 --resolver lts-13.11"
     MINGW_PATH_PART: "C:\\MinGW\\bin;"
     CONDA_DEPENDENCIES: "libpython"
   - PYV: "35"
     STACK_FLAGS: "--arch i386 --resolver lts-6.35"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "35"
#     STACK_FLAGS: "--arch i386 --resolver lts-9.21"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "35"
#     STACK_FLAGS: "--arch i386 --resolver lts-11.22"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "35"
#     STACK_FLAGS: "--arch i386 --resolver lts-12.26"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
   - PYV: "35"
     STACK_FLAGS: "--arch i386 --resolver lts-13.11"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
   - PYV: "36"
     STACK_FLAGS: "--arch i386 --resolver lts-6.35"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.6 libpython m2w64-toolchain"
   - PYV: "36"
     STACK_FLAGS: "--arch i386 --resolver lts-9.21"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.6 libpython m2w64-toolchain"
   - PYV: "36"
     STACK_FLAGS: "--arch i386 --resolver lts-11.22"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.6 libpython m2w64-toolchain"
   - PYV: "36"
     STACK_FLAGS: "--arch i386 --resolver lts-12.9"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.6 libpython m2w64-toolchain"
   - PYV: "37"
     STACK_FLAGS: "--arch i386 --resolver lts-6.35"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "37"
#     STACK_FLAGS: "--arch i386 --resolver lts-9.21"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "37"
#     STACK_FLAGS: "--arch i386 --resolver lts-11.22"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
#   - PYV: "37"
#     STACK_FLAGS: "--arch i386 --resolver lts-12.26"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
   - PYV: "37"
     STACK_FLAGS: "--arch i386 --resolver lts-13.11"
     MINGW_PATH_PART: ""
     CONDA_DEPENDENCIES: "python=3.5 libpython m2w64-toolchain"
# Building on x86_64 with m2w64 seems to tickle a ghc bug (see eg ghc
# trac #14576) Can't build without m2w64 on windows 64 bit with python
# 3.5 or later.  So don't bother to test these configurations for now.
# FWIW, hyphen has been tested with python 3.4 on 64-bit windows a
# while ago and that worked, but it involved messing with gendef.exe,
# and is only a solution for this fairly old python version anyway,
# and so I don't really have the energy to automate it in CI
#   - PYV: "36-x64"
#     STACK_FLAGS: "--arch x86_64 --resolver lts-12.9"
#     MINGW_PATH_PART: ""
#     CONDA_DEPENDENCIES: "python=3.6 libpython m2w64-toolchain"

test_script:
- "set PATH=%MINGW_PATH_PART%C:\\Miniconda%PYV%;C:\\Miniconda%PYV%\\Scripts;C:\\Python%PYV%;%PATH%"
- echo %PATH%
- conda create -y -q -n build-env %CONDA_DEPENDENCIES%
- activate build-env
- gcc --version
- stack %STACK_FLAGS% setup > nul
- stack %STACK_FLAGS% build
- stack %STACK_FLAGS% exec -- ghc --version
- stack %STACK_FLAGS% exec -- python --version
- stack %STACK_FLAGS% exec -- python hyphen\build-extn.py
- stack %STACK_FLAGS% exec -- python hyphen_examples_full.py
- stack %STACK_FLAGS% exec -- python test_tools/test_GIL_release.py fancy 5 5 5 12
- stack %STACK_FLAGS% exec -- python test_tools/test_GIL_release.py lazy 5 5 24 100
- stack %STACK_FLAGS% exec -- python hyphen\build-extn.py --not-threaded
- stack %STACK_FLAGS% exec -- python hyphen_examples_full.py
